export default {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  FAILED_LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  // LOAD_CART: 'LOAD_CART',
  ADD_TO_CART: 'ADD_TO_CART',
  PAY_PRODUCTS: 'PAY_PRODUCTS',
  FAILED_PAY_PRODUCTS: 'PAY_PRODUCTS',
  // DELETE_CART: 'DELETE_CART',
};
